### ISSUE TITLE
We should recommend people place their configs inside config/backpack/addon-name.php

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/addon-skeleton#3]
See title

**Comment by promatik** [comment]
Should it be inside a folder `addons` to differentiate the backpack official configs from the public addons?
```
config/backpack/addons/addon-name.php
```

**Comment by promatik** [comment]
**Note** that the #8 PR doesn't add that extra folder.

**Comment by tabacitu** [comment]
Changed my mind - sounds like a bad idea now. Sure, it'll be easier for the user. But since this will:
- make the Backpack organisation look responsible for that package we have no control over;
- make it super-difficult to install/create 2 addons with the same name;

I think it's better for each package to use its own namespace. So let's scrap this idea.

**Comment by promatik** [comment]
Ok makes sense now 😅
