### ISSUE TITLE
Translation string is ugly

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/addon-skeleton#5]
`create-dummy-operation::create-dummy-operation.line_name`

Right now it looks like we cannot use the vendorName as the namespace, because then a second project won't let us use the same namespace. So we can't do:
`promatik::create-dummy-operation.line_name`

**Comment by promatik** [comment]
I can confirm that for translations, we are able to use just the vendorName.
So this is valid;
`promatik::create-dummy-operation.line_name`
`promatik::another-dummy-operation.line_name`

We may have under the same publisher many packages, Laravel will load them all.

**Comment by promatik** [comment]
Now I'm wondering, since we can use the same vendorName for translations, should we use `backpack` instead of the user vendor name?

So, `backpack::create-dummy-operation.line_name` instead of `promatik::create-dummy-operation.line_name`?
Because on configs we are going to use the `backpack` directory ...

**Comment by tabacitu** [comment]
> Now I'm wondering, since we can use the same vendorName for translations, should we use backpack instead of the user vendor name?

I think that'll quickly become difficult to manage. And it'll prevent us (Backpack) from creating packages with a certain name, if somebody has already created 3rd party package with the same name. So I think it's better not to do that.

For consisteny across views, translations, etc - I think it's better to keep the ugly translation strings, rather than have one standard for views another one for translations, etc. So let's keep the `vendor-name.package-name` namespace.
